# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 06:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jejudaum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 31, 15, 32, 47, 347784)),
        ),
    ]
