# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jejudaum', '0002_auto_20170531_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
