# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jejudaum', '0003_auto_20170531_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='update_date',
        ),
    ]
